# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'blackMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for blackMovies
  # pod 'Moya', '~> 15.0'

  target 'blackMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'blackMoviesUITests' do
    # Pods for testing
  end

end
